1698 refactor element tree
codelab-ai/builder pull request #1733
Opened 2022-08-16 11:37 UTC by phmngocnghia

## Description (Optional)

## Related Issue(s)

Fixes #

2022-08-29 02:11 UTC, webberwang requested changes

2022-08-29 02:11 UTC, webberwang commented on libs/frontend/modules/element/src/store/element.service.ts
> +    const hydratedElements = this.hydrateOrUpdateCache(elements)
Could extract logic to 3 functions at the top level

`addChildElement` and `addNextSibling` or `addPrevSibling`

Then the 2 siblings functions would share code from a third function

2022-08-29 02:23 UTC, webberwang commented on libs/backend/src/schema/element.schema.ts
> +    nextSibling: Element @relationship(type: "TREE_NODE", direction: IN)
shouldn't the relationship be "NODE_SIBLING"

"TREE_NODE" doesn't give us any indication about sibling relationship

2022-08-29 02:23 UTC, webberwang commented on libs/backend/src/schema/element.schema.ts
> +    childrenRoot: Element @relationship(type: "TREE_ROOT", direction: IN)
this should be "TREE_SUB_ROOT", since a tree only has 1 root

2022-08-29 02:23 UTC, webberwang commented on libs/frontend/modules/element/src/store/element.model.ts
> +  linkSiblings({
To clarify, we still need the conditional somewhere. We're just pushing it to the top most calling level, so as close to the event source as possible.

2022-08-29 03:44 UTC, phmngocnghia commented on libs/frontend/modules/element/src/store/element.model.ts
> +  syncLinkedSiblings() {
this fn is for orchestrating update state when moving an element, so adding, and removing element could happen at the same time and result in a batched state change, and prevent layout shift https://github.com/codelab-ai/builder/blob/347547fee4fc5ea3c803ab64c87d0a0dc53554fe/libs/frontend/modules/element/src/store/element.service.ts#L558

2022-08-29 04:06 UTC, webberwang commented on libs/frontend/modules/element/src/store/element.model.ts
> +  syncLinkedSiblings() {
Ah i see you left a comment there. Could you

- [ ] Move the comment to the class method (I think this is a better place to add it)
- [ ] Change name to something more appropriate, such as `syncCacheForSiblingLinks`

LinkedSiblings is more about the siblings, but SiblingLinks is focusing on the link. Ins this case I think it's more about the links

2022-08-31 03:35 UTC, webberwang requested changes

2022-08-31 10:19 UTC, webberwang requested changes

2022-08-31 10:19 UTC, webberwang commented on libs/frontend/modules/element/src/use-cases/element/create-element/CreateElementModal.tsx
> +      const prevSibling = prevSiblingId
why can't we use prevSiblingId directly?

2022-08-31 10:19 UTC, webberwang commented on libs/frontend/modules/element/src/use-cases/element/move-element/MoveElementForm.tsx
> +        prevSiblingId: currentPrevsiblingId,
note the camel case

2022-08-31 10:19 UTC, webberwang commented on libs/frontend/modules/element/src/use-cases/element/move-element/MoveElementForm.tsx
> +      if (changeParent && parentElementId) {
We should have a domain specific function that takes in parameters like sibling, parent etc

`shouldMoveAsSubRoot` etc

2022-08-31 10:19 UTC, webberwang commented on libs/shared/abstract/core/src/domain/element/element.service.interface.ts
> +  linkElement(props: {
this no longer exists right?

2022-08-31 10:19 UTC, webberwang commented on package.json
> +    "ogmgen:builder": "cross-env GENERATE_OGM_TYPES=true nx serve builder",
builder doesn't seem necessary since landing would never have ogm types

2022-08-31 10:38 UTC, webberwang requested changes

2022-08-31 10:38 UTC, webberwang commented on libs/frontend/modules/element/src/store/element.service.ts
> +  moveElementNextTo = _async(function* (
`moveElementAsNextSibling` sounds more fitting to our domain

2022-08-31 10:38 UTC, webberwang commented on libs/frontend/modules/element/src/use-cases/element/create-element/CreateElementModal.tsx
>        const [element] = await elementService.create([data])
The create here should be called inside our "Use Case Driven Function" `createElementAsNextSibling`, `createElementAsRootChild`, `moveElementAsRootChild`, `moveElementAsNextSibling` etc

2022-09-01 03:39 UTC, phmngocnghia commented on libs/frontend/modules/element/src/store/element.model.ts
> +  attachToParent(parentElementId: string) {
yes, in case we don't need to attach to subroot. We won't need to attach to parent if we make parent as a computed property. This is just for the current implementation context

2022-09-01 04:34 UTC, webberwang commented on libs/frontend/modules/element/src/store/element.model.ts
> +  attachToParent(parentElementId: string) {
Which use case would we not attach as subRoot?

2022-09-02 14:22 UTC, merged

2022-09-02 14:22 UTC, webberwang commented
think we've refactored enough, I'll check take a look down the line