Enum type dropdown
codelab-ai/builder pull request #1741
Opened 2022-08-20 15:01 UTC by mohasarc

## Description (Optional)

## Related Issue(s)

Fixes #1670

2022-08-23 03:00 UTC, webberwang requested changes

2022-08-23 03:00 UTC, webberwang commented on libs/frontend/modules/type/src/props-form/form-controls/Field.tsx
>    field: IField
We could make `IField<T = IAnyType>`, so it allows us to pass a more specific subtype so we don't have to cast

2022-08-23 19:43 UTC, mohasarc commented on libs/frontend/modules/type/src/props-form/form-controls/Field.tsx
>    field: IField
Making `IField` generic alone did not fix the issue because aparently typescript does not infer the type in switch statements over nested properties (https://stackoverflow.com/questions/65139900/why-doesnt-typescript-infer-type-in-switch-statements-over-deep-nested-properti). So I had to change the switch statement into if/return clauses applying the workaround outlined in the same stackoverflow link.

2022-08-23 19:45 UTC, mohasarc commented on libs/frontend/modules/type/src/props-form/form-controls/Field.tsx
>  })
@webberwang This is the change.

2022-08-25 07:17 UTC, webberwang commented on libs/frontend/modules/type/src/props-form/form-controls/Field.tsx
>  })
yeah this is a good solution, thanks

2022-08-25 07:18 UTC, merged