feat: import/export tag in seed data
codelab-ai/builder pull request #1750
Opened 2022-08-23 07:55 UTC by phmngocnghia

## Description (Optional)

## Related Issue(s)

Fixes #

2022-08-23 11:00 UTC, webberwang requested changes
Our import tag logic should upsert tag using existing id, if we use name, we won't be able to update tag names.

App upsert uses id which is correct

2022-08-24 06:30 UTC, webberwang requested changes

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/use-cases/parser/ant-design.ts
> +export const createAntdesignTagsData = async () => {
Can we add a signature here

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/commands/import/import-seed-data/import-seed-data.ts
>  export const __seedData = async (selectedUser: string) => {
This should be broken into 2 functions `__seedAtomFromParser` & `__seedAtomWithTags` etc

The `__seedAtomFromParser` is already ran by admin and likely won't need to be run again

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/commands/import/import-seed-data/import-seed-data.ts
> +  createAntdesignTagsData,
use `AntDesign` for naming

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/repository/atom.repo.ts
>    if (!idExisting.length) {
`existingId` reads better or `existingAtomId`

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/repository/tag.repo.ts
> +  const nameExisting = await Tag.find({
`existingName` is more grammatically correct

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/use-cases/import/import-tags.ts
> +  const promiseCreateTags = tags.map((tag) => {
`createTagsOperations`

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/use-cases/import/import-tags.ts
> +  const promiseSyncTags = tags.map((tag) => {
`syncTagsOperations`, the fact it's a promise shouldn't have to be reflected in the time, it's just a technicality, not a domain concern

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/use-cases/parser/ant-design.ts
> +import { antTagNames } from '../../commands/import/import-seed-data/add-antd-use-case-tags'
`add-antd-tags` is good

2022-08-24 06:30 UTC, webberwang commented on apps/cli/src/use-cases/parser/ant-design.ts
> +export const createAntdesignTagsData = async () => {
`AntDesign` naming

2022-08-24 06:30 UTC, webberwang commented on libs/shared/abstract/core/src/domain/tag/tag.dto.interface.ts
> +  name?: string
why couldn't we make `id` & `name` required?

2022-08-25 02:21 UTC, phmngocnghia commented on apps/cli/src/commands/import/import-seed-data/import-seed-data.ts
>  export const __seedData = async (selectedUser: string) => {
![image](https://user-images.githubusercontent.com/36730355/186559265-8a86c8a5-47c7-4903-9153-a50523d1717f.png)

@webberwang do you mean something like this? `__seedAtomFromParser ` is old fn, and `__seedAtomWithTags ` is a new fn accepting atoms as parameter, transform, and update them

2022-08-25 06:46 UTC, webberwang commented on apps/cli/src/commands/import/import-seed-data/import-seed-data.ts
>  export const __seedData = async (selectedUser: string) => {
I mean usage would be like this, we can individually comment out different types of seeder

![builder_–_import_command_ts](https://user-images.githubusercontent.com/26264925/186594249-ab12a8f9-a400-4191-8563-85ebca2d3f9c.jpg)

2022-08-29 02:29 UTC, webberwang commented on apps/cli/src/repository/tag.repo.ts
> +  const connectChildrens =
children is already the plural

2022-08-29 02:35 UTC, webberwang commented on apps/cli/src/repository/tag.repo.ts
> +export const linkTag = async (tag: ITagExport) => {
The function name could be bit more descriptive, linkTag to what?

something like `connectChildTagToParent` would be better. long function names are okay

2022-08-30 07:17 UTC, webberwang requested changes

2022-08-31 03:38 UTC, webberwang requested changes

2022-08-31 03:38 UTC, webberwang commented on apps/cli/src/commands/import/import.command.ts
> +    // await __seedData(selectedUser, antdAtomsFactory)
This function no longer exists right

2022-09-02 15:02 UTC, merged