refactor: element svc
codelab-ai/builder pull request #1789
Opened 2022-09-06 11:42 UTC by phmngocnghia

## Description (Optional)

## Related Issue(s)

Fixes #

2022-09-08 05:00 UTC, webberwang requested changes

2022-09-08 05:00 UTC, webberwang commented on libs/frontend/modules/element/src/store/element.model.ts
>      return makePatchElementInput(sibling, {
what is different between patch and update? why not call it `makeUpdateElementInput`?

2022-09-08 06:24 UTC, phmngocnghia commented on libs/frontend/modules/element/src/store/element.model.ts
>      return makePatchElementInput(sibling, {
It accepts `element` param to fill in the `where`

2022-09-08 06:27 UTC, webberwang commented on libs/frontend/modules/element/src/store/element.model.ts
>      return makePatchElementInput(sibling, {
is update name already taken?

2022-09-08 06:42 UTC, phmngocnghia commented on libs/frontend/modules/element/src/graphql/element.endpoints.graphql.custom.ts
>      BatchUpdateElements(
![image](https://user-images.githubusercontent.com/36730355/189052392-64f73bd4-936c-48dc-9997-3453f7d926f3.png)

we can update many elements with multiple changes but with only one joined condition containing multiple where. Like

Update "a=1" where "b=1 or c=2"....

I need a function that would update
- a=1 when b=1
- b=2 when c =1
- ... etc

2022-09-08 06:50 UTC, webberwang commented on libs/frontend/modules/element/src/graphql/element.endpoints.graphql.custom.ts
>      BatchUpdateElements(
okay my mistake, I thought batching mutations had issues?

2022-09-08 13:29 UTC, webberwang requested changes
some rebase issue, also don't use abbreviations, use `service` instead of `svc`

2022-09-09 06:38 UTC, phmngocnghia commented
https://github.com/codelab-ai/builder/pull/1789/files#diff-d8d2d09015339cd1dec0bd1332df7fafb6073251273d4a1608109e04cd284c94 this file is not used anywhere

2022-09-09 09:00 UTC, merged