feat: implement landing page
codelab-ai/builder pull request #1790
Opened 2022-09-07 08:19 UTC by hauleIT

## Description (Optional)

## Related Issue(s)

Fixes #1761

2022-09-07 09:05 UTC, webberwang requested changes

2022-09-08 13:27 UTC, webberwang requested changes
check out the ci lint, one of the commit message had improper format

2022-09-08 13:27 UTC, webberwang commented on apps/landing/home/pricing/PricingBody.tsx
> +    bgColor: '#F3ECFF',
these color we shouldn't hardcode, use a tailwind preset

2022-09-09 03:39 UTC, webberwang requested changes

2022-09-09 03:39 UTC, webberwang commented on apps/landing/home/pricing/PricingBody.tsx
> +    case 'textViolet700':
why not just inline this in the object

2022-09-09 03:47 UTC, hauleIT commented on apps/landing/home/pricing/PricingBody.tsx
> +    case 'textViolet700':
I tried, but twin.marco can not read property 'replace'

2022-09-09 03:48 UTC, hauleIT commented on apps/landing/home/pricing/PricingBody.tsx
> +    case 'textViolet700':
It's just using String

2022-09-13 04:02 UTC, merged