Fix errors when re-ordering using dnd
codelab-ai/builder pull request #1822
Opened 2022-09-13 14:52 UTC by melhamin

This PR fixes errors while re-ordering elements using dnd.

## Description (Optional)

## Related Issue(s)

Fixes #1780

2022-09-13 15:00 UTC, webberwang requested changes

2022-09-13 15:00 UTC, webberwang commented on libs/frontend/modules/element/src/store/element.service.ts
> +      element.attachPrevToNextSibling(),
For all these, if we used `element.attachPrevToNextSibling` and removed the `() => {}` inside the method, would that work?

2022-09-13 15:09 UTC, melhamin commented on libs/frontend/modules/element/src/store/element.service.ts
> +      element.attachPrevToNextSibling(),
I believe it should work.

2022-09-13 15:12 UTC, melhamin commented on libs/frontend/modules/element/src/store/element.service.ts
> +      element.attachPrevToNextSibling(),
No sorry it doesn't work

2022-09-14 13:05 UTC, webberwang requested changes
Could remove the custom element endpoint for the batch mutation since that can cause issues

2022-09-14 17:35 UTC, merged